// 30 SHAP intro descriptions
export const SHAP_INTRO_TEXTS = [
  "The chart below shows how your selected market factors influenced the latest price forecast. Positive values push the prediction higher, while negative values pull it lower.",
  "Each bar represents a market variable's contribution to the forecast. Green bars indicate upward pressure on gold prices, while red bars signal downward influence.",
  "Here's a breakdown of how each selected factor shaped the forecast. The longer the bar, the stronger the influence on the predicted gold price.",
  "This visualization reveals which factors are driving the forecast up or down. Use it to understand the key forces behind the projected price movement.",
  "The following chart quantifies how each market indicator contributed to the current gold price prediction. Positive impacts suggest bullish pressure; negative impacts suggest bearish pressure.",
  "Explore how your chosen variables interact to shape the forecast. Each bar measures the magnitude and direction of influence on the predicted gold price.",
  "Below you'll see the relative weight of each factor in determining the forecast. Larger bars indicate stronger influence, with color showing the direction.",
  "This analysis breaks down the forecast into individual contributions from each market factor. Together, they explain why the model expects gold to move in this direction.",
  "Understanding what drives the prediction is just as important as the number itself. Each bar shows a factor's net effect on the forecasted gold price.",
  "The drivers chart illustrates which economic forces are pushing gold prices up and which are holding them back, based on your selected variables.",
  "Each factor's contribution is measured independently. Green indicates the factor supports higher gold prices, while red suggests downward pressure.",
  "This chart helps you see beyond the forecast number. It reveals the underlying economic dynamics that shaped the prediction.",
  "Your selected variables each play a role in the forecast. The chart below shows the direction and strength of each factor's influence.",
  "Think of each bar as a vote: green bars vote for higher prices, red bars vote for lower prices. The net result shapes the final forecast.",
  "The influence chart below decomposes the forecast into actionable insights. See which macro factors matter most for gold's near-term trajectory.",
  "Market factors rarely move in isolation. This chart shows how each selected variable independently contributes to the overall gold price forecast.",
  "The bars below represent each factor's isolated impact on the prediction. Use this to identify which economic trends matter most right now.",
  "Every forecast tells a story. The chart below reveals which chapters — inflation, rates, commodities — are writing gold's next price move.",
  "Below is a factor-by-factor breakdown of the forecast. Positive contributions push gold higher; negative contributions act as headwinds.",
  "This explainability chart connects the dots between macroeconomic trends and the gold price outlook, showing each variable's individual impact.",
  "Wondering why gold is forecast to move this way? The chart below attributes the prediction to specific market forces you've selected.",
  "Each bar quantifies a single factor's pull on the forecast. Together, they paint a complete picture of the forces shaping gold's trajectory.",
  "The magnitude of each bar reflects how sensitive the gold forecast is to that particular market variable. Longer bars deserve more attention.",
  "This breakdown shows the net effect of each predictor on the gold outlook. It helps separate noise from the signals that truly matter.",
  "Gold prices respond to a web of economic forces. The chart below untangles that web, showing each thread's individual contribution.",
  "Use this chart to assess which macro drivers are currently most relevant to gold. The direction and size of each bar tell the story.",
  "The forecast isn't a black box. Below, each factor's contribution is laid out transparently so you can evaluate the reasoning yourself.",
  "From inflation to commodities, each factor exerts its own force on gold. See how they stack up in the contribution chart below.",
  "The explainability view below shows the 'why' behind the 'what'. Each bar is a window into the economic logic of the forecast.",
  "Data-driven insights start here. The chart maps each selected variable's effect on the prediction, giving you clarity on what's moving gold.",
];

// 30 detailed investor-grade Key Takeaway texts
export const SHAP_TAKEAWAY_TEXTS = [
  "Inflation remains the single most powerful tailwind for gold in this forecast. With consumer price pressures persisting above central bank targets, institutional and retail investors alike continue to rotate into gold as a proven inflation hedge. Meanwhile, rising interest rates exert downward pressure by increasing the opportunity cost of holding a non-yielding asset. However, the net effect is decisively positive — the magnitude of inflation-driven demand significantly outweighs the drag from higher rates. For investors, this suggests that gold allocations remain well-supported in the current macro environment, particularly as real yields (adjusted for inflation) stay compressed.",

  "The interplay between the S&P 500 and gold highlights a classic risk-on vs. risk-off dynamic. When equities rally, capital tends to flow away from safe-haven assets, weakening gold demand. In this forecast, equity strength is a modest headwind. However, it is more than offset by silver's co-movement and persistent inflation expectations. Investors should note that during periods of simultaneous equity and inflation strength — a hallmark of late-cycle environments — gold often outperforms expectations as portfolio diversification demand increases.",

  "Interest rates are the most significant bearish factor in this analysis, reflecting central bank tightening designed to cool inflation. Higher rates make bonds and savings accounts more attractive relative to gold. Yet the forecast remains net positive because inflation expectations — the very problem rates are trying to solve — continue to dominate investor behavior. This creates a paradox familiar to seasoned gold investors: the medicine (rate hikes) hasn't yet cured the disease (inflation), and until it does, gold benefits from both the symptom and the uncertainty around the cure.",

  "Silver prices are contributing meaningfully to the bullish gold outlook. Historically, silver and gold exhibit a strong positive correlation, and when silver rallies — often driven by a mix of industrial demand and precious metal sentiment — gold tends to follow. This cross-asset signal reinforces the broader theme of precious metal strength. For portfolio construction purposes, the aligned movement of both metals suggests that the current rally is broad-based rather than driven by a single idiosyncratic factor, lending greater conviction to the forecast.",

  "The 10-year government bond yield is acting as a headwind, which is expected when yields climb. Higher bond yields offer investors a competing safe return, reducing the relative attractiveness of gold. However, the impact here is moderate (-15), suggesting that bond markets have not yet reached yield levels that would trigger a significant reallocation away from gold. As long as inflation-adjusted (real) yields remain low or negative, gold's appeal as a store of value persists despite rising nominal rates.",

  "Copper prices are providing a secondary but notable tailwind for gold. Rising copper is typically a signal of robust global industrial activity and, by extension, inflationary pressure from the demand side. For gold investors, this matters because demand-pull inflation tends to be more persistent than supply-shock inflation, creating a longer runway for gold's hedge premium. The copper signal effectively corroborates the inflation narrative that is the primary driver of this forecast.",

  "The current variable combination paints a picture of an economy in transition: inflation remains stubborn, commodities are firm, and central banks are tightening. For gold, this transitional phase is historically supportive. The metal thrives in environments of uncertainty, and few things create more uncertainty than the tension between persistent inflation and aggressive monetary policy. Investors positioned in gold during similar past episodes — the late 1970s, early 2000s, and 2020–2022 — were rewarded with meaningful appreciation.",

  "This forecast is underpinned by a convergence of macro forces that collectively favor gold. On the bullish side, inflation expectations, silver correlation, and copper-driven industrial signals all point higher. On the bearish side, interest rates and bond yields push back — but with notably smaller magnitudes. The asymmetry is important: there are more forces pulling gold up, and they are individually stronger, than the forces pulling it down. This imbalance supports a moderately confident bullish stance.",

  "For risk-conscious investors, the key message is diversification resilience. Gold's positive forecast even in the face of rising rates demonstrates its unique role in multi-asset portfolios. While equities may offer higher returns in benign conditions, gold provides asymmetric protection during stress events. The current forecast variables suggest we are in a regime where both growth and inflation are elevated — precisely the scenario where a 5–15% gold allocation has historically improved portfolio Sharpe ratios.",

  "The S&P 500's negative contribution to the gold forecast deserves nuanced interpretation. It does not mean equities are crashing — rather, it means equity strength is diverting some marginal capital away from gold. But this effect is small relative to the inflation tailwind. Sophisticated investors understand that gold and equities can both rise simultaneously when inflation is the driving force, because gold responds to purchasing power erosion while equities respond to nominal earnings growth. This is not a zero-sum relationship.",

  "Inflation expectations are contributing +45 to this forecast — the largest single factor. To put this in context, when inflation expectations rise by 1 percentage point, gold has historically appreciated by 8–12% over the following quarter. The current reading suggests the market is pricing in continued above-target inflation, which directly benefits gold holders. Investors who are underweight gold relative to their inflation exposure may want to consider rebalancing.",

  "The combined precious metals signal (silver + gold correlation) adds conviction to the bullish case. When silver leads or confirms gold's move, it typically indicates genuine monetary demand for hard assets rather than speculative froth. Silver's dual role as both an industrial and monetary metal makes it a useful barometer of whether gold's rally has fundamental support. In this case, silver's positive contribution (+22) suggests the rally is fundamentally grounded.",

  "From a macro regime perspective, the current factor mix resembles a 'stagflation-lite' environment: growth is not collapsing, but inflation is sticky, and monetary policy is tightening without fully cooling prices. Gold has historically been the best-performing major asset class in stagflationary periods, with average real returns of 12–15% annually. While we are not in full stagflation, the directional similarity is enough to keep gold's risk premium elevated.",

  "Interest rate headwinds (-32) are significant but contextually manageable. Central banks are near or at terminal rates in this cycle, which means the incremental bearish pressure from further hikes is diminishing. If rates plateau or begin to decline — as forward curves currently suggest — the interest rate drag on gold could flip to a tailwind within 2–3 quarters. Forward-looking investors may see the current forecast as conservative relative to the potential upside if policy pivots materialize.",

  "The forecast reflects a market where uncertainty itself is a commodity, and gold is its primary beneficiary. Geopolitical tensions, fiscal deficits, de-dollarization trends, and central bank gold purchases all operate in the background of these visible factors. While not explicitly modeled as separate variables, their influence flows through inflation expectations and commodity prices. For investors, this means the stated forecast may understate gold's true upside in tail-risk scenarios.",

  "Copper's positive contribution (+12) may seem modest, but it carries disproportionate informational value. Copper — often called 'Dr. Copper' for its ability to diagnose economic health — is signaling that global demand remains resilient. This resilience supports commodity prices broadly, including gold, and suggests that any economic slowdown is unlikely to be deflationary. For gold investors, the absence of deflationary risk is as important as the presence of inflationary drivers.",

  "The balance of factors suggests a favorable risk-reward profile for gold over the forecast horizon. The downside is bounded by persistent inflation support, while the upside is open-ended if geopolitical or financial stress events materialize. This asymmetric payoff structure is one of gold's most valuable portfolio characteristics and is fully reflected in the current forecast's confidence-weighted price range.",

  "Bond yields and interest rates together contribute roughly -47 points of bearish pressure, while inflation and commodity factors contribute approximately +79 points of bullish pressure. This 32-point net positive spread is what drives the forecast higher. Investors should monitor this spread: if rate hikes accelerate without a corresponding decline in inflation, the spread narrows and the forecast becomes less certain. Conversely, any easing in monetary policy would widen the spread and strengthen the gold case.",

  "For allocation purposes, this forecast supports maintaining or modestly increasing gold exposure within diversified portfolios. The multi-factor analysis shows that gold's bullish drivers are diverse (inflation, silver, copper) rather than concentrated in a single theme. Diversified bullish support historically leads to more sustainable price trends compared to single-factor rallies, which tend to reverse sharply when that factor fades.",

  "The S&P 500's dampening effect on gold (-18) is a reminder that asset allocation is about trade-offs, not absolutes. In the current environment, equities and gold are both viable holdings — they serve different purposes. Equities capture nominal growth, while gold preserves real purchasing power. The forecast suggests both can coexist profitably, but if forced to choose a marginal dollar of allocation, the inflation-driven tailwinds give gold a slight edge over the forecast horizon.",

  "Silver's strong co-movement with gold in this forecast is a signal that precious metals are being driven by monetary factors — inflation hedging, currency debasement concerns, and central bank diversification — rather than purely industrial demand. This monetary driver tends to produce longer-lasting gold rallies compared to those driven by speculative positioning. Investors can take some comfort that the current move appears fundamentally supported.",

  "The forecast's confidence level reflects the stability of the underlying factor contributions. When all major factors are included, the model has a richer information set and can make more robust predictions. Removing variables reduces confidence not because the forecast is wrong, but because there is less corroborating evidence. Investors should interpret the confidence metric as a measure of informational completeness, not a probability of profit.",

  "From a tactical perspective, the negative contribution of interest rates creates a potential catalyst for further gold upside. If upcoming economic data disappoints and central banks signal a pause or pivot, the removal of this headwind could unlock an additional 3–5% of price appreciation beyond the current forecast. Rate-sensitive investors may want to position for this optionality by establishing gold exposure before policy meetings.",

  "The multi-variable approach used here provides a more nuanced view than single-factor gold models. By considering the interaction of equities, rates, bonds, inflation, and commodities simultaneously, the forecast captures second-order effects that simple models miss. For example, rising copper prices increase inflation expectations, which in turn boost gold — a chain reaction that single-factor analysis would undercount.",

  "For long-term investors, the most important takeaway is that gold's structural supports remain intact. Central bank buying (reflected indirectly through commodity and inflation channels), de-dollarization trends, and fiscal deficit concerns all create a floor under gold prices. The current forecast's variables capture the cyclical overlay on top of these structural trends, and both layers currently point in the same direction: moderately bullish.",

  "The relatively modest impact of the 10-year bond yield (-15) compared to interest rates (-32) is noteworthy. It suggests that the bond market is partially discounting future rate cuts, which limits the yield curve's drag on gold. When short-term rates are high but long-term rates are contained, it often signals that markets expect policy easing ahead — a scenario that would be distinctly positive for gold prices in subsequent quarters.",

  "Investors should pay special attention to the inflation factor's dominance in this forecast. At +45, it contributes more than any individual bearish factor alone. This single-factor dominance means that the trajectory of inflation data — CPI releases, PCE readings, wage growth reports — will have an outsized impact on whether this forecast is achieved, exceeded, or undershot. Positioning ahead of major inflation data releases could offer tactical advantages.",

  "The commodity complex (silver + copper) collectively contributes +34 to the forecast, making it the second-largest bullish theme after inflation. This broad commodity strength is consistent with a super-cycle thesis that many institutional investors are exploring. If the commodity super-cycle continues, gold stands to benefit not only from direct demand but from the inflationary spillover that commodity rallies create across the broader economy.",

  "Risk management considerations: while the forecast is bullish, the confidence band reflects meaningful uncertainty. The price range between the lower and upper bounds represents the forecast's acknowledgment that macro conditions can shift rapidly. Investors should size gold positions according to their risk tolerance, using the lower bound as a stress-test level and the upper bound as an optimistic but achievable target.",

  "In summary, the weight of evidence from the selected variables supports a constructive outlook for gold. The bullish factors are more numerous and individually stronger than the bearish ones. The macro backdrop — persistent inflation, firm commodity prices, and an equity market that hasn't yet derailed safe-haven demand — is favorable. For investors seeking to preserve purchasing power and diversify portfolio risk, gold remains a compelling allocation at current levels.",
];
